sudo: required
services: 
  - docker

before_install:
  - docker build -t ddavisjr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ddavisjr/react-test npm test -- --coverage

after_success:
  - docker build -t ddavisjr/multi-client ./client
  - docker build -t ddavisjr/multi-nginx  ./nginx
  - docker build -t ddavisjr/multi-server ./server
  - docker build -t ddavisjr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push ddavisjr/multi-client
  - docker push ddavisjr/multi-nginx
  - docker push ddavisjr/multi-server
  - docker push ddavisjr/multi-worker